In [2]:
!pip install opencv-python

In [3]:
!pip install pillow

In [4]:
from PIL import Image
import numpy as np
import os

def preprocess_fraction_dataset(folder_path, image_size=(28, 28)):
    images = []
    labels = []

    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)

        # Load the image with PIL
        with Image.open(file_path) as img:
            img = img.convert('L')  # Convert to grayscale
            img = img.resize(image_size)  # Resize image
            image = np.array(img)  # Convert to numpy array

        # Normalize the image
        image = image.astype(np.float32) / 255.0

        # Extract label from filename
        # Adjust the logic below based on your actual filename format
        label_parts = filename.split('.')[0].split('_')
        label = [int(part) for part in label_parts if part.isdigit()]

        images.append(image)
        labels.append(label)

    images = np.array(images)
    labels = np.array(labels)

    return images, labels

# Usage
# Usage
folder_path = 'data/fraction'
images, labels = preprocess_fraction_dataset(folder_path)

# Print the shape of the arrays
print("Images shape:", images.shape)
print("Labels shape:", labels.shape)

# Optionally, print the first few entries
print("First few images:", images[:3])
print("First few labels:", labels[:3])



Images shape: (3167, 28, 28)
Labels shape: (3167, 3)
First few images: [[[1.         1.         0.99607843 ... 1.         1.         1.        ]
  [0.99607843 0.99215686 0.9882353  ... 1.         1.         1.        ]
  [0.99607843 0.99607843 1.         ... 1.         1.         1.        ]
  ...
  [1.         1.         1.         ... 0.7882353  0.95686275 0.9882353 ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]]

 [[1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  ...
  [1.         1.         1.         ... 0.8156863  0.9411765  0.9843137 ]
  [1.         1.         1.         ... 0.99215686 0.9882353  0.9882353 ]
  [1.         1.         1.         ... 1.         1.         1.        ]]

 [[1.         1.         

In [5]:
from PIL import Image
import numpy as np
import os

def preprocess_dataset(data_folder, image_size=(28, 28)):
    images = []
    labels = []

    # Iterate through each class folder
    for class_name in os.listdir(data_folder):
        class_folder = os.path.join(data_folder, class_name)

        # Check if it's a directory
        if os.path.isdir(class_folder):
            for filename in os.listdir(class_folder):
                file_path = os.path.join(class_folder, filename)

                # Load the image with PIL
                with Image.open(file_path) as img:
                    img = img.convert('L')  # Convert to grayscale
                    img = img.resize(image_size)  # Resize image
                    image = np.array(img)  # Convert to numpy array

                # Normalize the image
                image = image.astype(np.float32) / 255.0

                images.append(image)
                labels.append(class_name)  # Use folder name as class label

    images = np.array(images)
    labels = np.array(labels)

    return images, labels

# Usage
data_folder = 'data/'
images, labels = preprocess_dataset(data_folder)

# Print the shape of the arrays
print("Images shape:", images.shape)
print("Labels shape:", labels.shape)

# Optionally, print the first few entries
print("First few images:", images[:3])
print("First few labels:", labels[:3])


Images shape: (72159, 28, 28)
Labels shape: (72159,)
First few images: [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
First few labels: ['0' '0' '0']


In [6]:
from PIL import Image
import numpy as np
import os

def preprocess_fraction_dataset(folder_path, image_size=(28, 28)):
    images = []
    labels = []

    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)

        # Load the image with PIL
        with Image.open(file_path) as img:
            img = img.convert('L')  # Convert to grayscale
            img = img.resize(image_size)  # Resize image
            image = np.array(img)  # Convert to numpy array

        # Normalize the image
        image = image.astype(np.float32) / 255.0

        # Extract label from filename
        label_parts = filename.split('.')[0].split('_')
        label = [int(part) for part in label_parts if part.isdigit()]

        images.append(image)
        labels.append(label)

    images = np.array(images)
    labels = np.array(labels)

    return images, labels


In [7]:
from PIL import Image
import numpy as np
import os

def preprocess_fraction_dataset(base_folder, image_size=(28, 28)):
    images = []
    labels = []

    # Iterate through each class folder
    for class_folder in os.listdir(base_folder):
        class_folder_path = os.path.join(base_folder, class_folder)

        # Check if it's indeed a directory
        if os.path.isdir(class_folder_path):
            for filename in os.listdir(class_folder_path):
                file_path = os.path.join(class_folder_path, filename)

                # Check if it's a file, not a sub-directory
                if os.path.isfile(file_path):
                    # Load the image with PIL
                    with Image.open(file_path) as img:
                        img = img.convert('L')  # Convert to grayscale
                        img = img.resize(image_size)  # Resize image
                        image = np.array(img)  # Convert to numpy array

                    # Normalize the image
                    image = image.astype(np.float32) / 255.0

                    images.append(image)
                    labels.append(class_folder)  # Use folder name as class label

    images = np.array(images)
    labels = np.array(labels)

    return images, labels

# Usage
folder_path = 'data/'
images, labels = preprocess_fraction_dataset(folder_path)

# Print the shape of the arrays to verify
print("Images shape:", images.shape)
print("Labels shape:", labels.shape)

Images shape: (72159, 28, 28)
Labels shape: (72159,)


In [17]:
import tensorflow as tf

def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(11, activation='softmax')  # Adjust based on the label structure
    ])
    return model

model = create_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [18]:
# Reshape images for the CNN and train the model
images_train = images_train.reshape((-1, 28, 28, 1))  # Reshape for the CNN
history = model.fit(images_train, labels_train, epochs=10, batch_size=32, validation_split=0.1)


Epoch 1/10
1624/1624 [==============================] - 8s 4ms/step - loss: 0.1516 - accuracy: 0.9541 - val_loss: 0.0703 - val_accuracy: 0.9790
Epoch 2/10
1624/1624 [==============================] - 8s 5ms/step - loss: 0.0492 - accuracy: 0.9848 - val_loss: 0.0449 - val_accuracy: 0.9875
Epoch 3/10
1624/1624 [==============================] - 7s 4ms/step - loss: 0.0329 - accuracy: 0.9895 - val_loss: 0.0431 - val_accuracy: 0.9884
Epoch 4/10
1624/1624 [==============================] - 7s 4ms/step - loss: 0.0244 - accuracy: 0.9925 - val_loss: 0.0462 - val_accuracy: 0.9874
Epoch 5/10
1624/1624 [==============================] - 7s 5ms/step - loss: 0.0196 - accuracy: 0.9935 - val_loss: 0.0462 - val_accuracy: 0.9856
Epoch 6/10
1624/1624 [==============================] - 7s 4ms/step - loss: 0.0141 - accuracy: 0.9951 - val_loss: 0.0429 - val_accuracy: 0.9870
Epoch 7/10
1624/1624 [==============================] - 8s 5ms/step - loss: 0.0121 - accuracy: 0.9957 - val_loss: 0.0430 - val_accuracy:

In [16]:
print("Labels data type:", labels_train.dtype)


Labels data type: int32


In [13]:
# Assuming 'labels' contains all your string labels
unique_labels = np.unique(labels)
label_to_int = {label: i for i, label in enumerate(unique_labels)}


In [19]:
# Convert the full labels array
labels_int = np.array([label_to_int[label] for label in labels])

# Now split the dataset again with the integer labels
images_train, images_test, labels_train, labels_test = train_test_split(
    images, labels_int, test_size=0.2, random_state=42
)


In [20]:
print("Labels data type:", labels_train.dtype)


Labels data type: int32


In [23]:
# Reshape images for the CNN
images_train_reshaped = images_train.reshape((-1, 28, 28, 1))

# Train the model
history = model.fit(images_train_reshaped, labels_train, epochs=10, batch_size=32, validation_split=0.1)


Epoch 1/10
1624/1624 [==============================] - 11s 6ms/step - loss: 0.1527 - accuracy: 0.9530 - val_loss: 0.0501 - val_accuracy: 0.9844
Epoch 2/10
1624/1624 [==============================] - 10s 6ms/step - loss: 0.0470 - accuracy: 0.9860 - val_loss: 0.0441 - val_accuracy: 0.9867
Epoch 3/10
1624/1624 [==============================] - 11s 6ms/step - loss: 0.0317 - accuracy: 0.9901 - val_loss: 0.0373 - val_accuracy: 0.9894
Epoch 4/10
1624/1624 [==============================] - 11s 7ms/step - loss: 0.0228 - accuracy: 0.9929 - val_loss: 0.0398 - val_accuracy: 0.9880
Epoch 5/10
1624/1624 [==============================] - 11s 7ms/step - loss: 0.0174 - accuracy: 0.9941 - val_loss: 0.0448 - val_accuracy: 0.9891
Epoch 6/10
1624/1624 [==============================] - 11s 7ms/step - loss: 0.0146 - accuracy: 0.9951 - val_loss: 0.0462 - val_accuracy: 0.9870
Epoch 7/10
1624/1624 [==============================] - 10s 6ms/step - loss: 0.0099 - accuracy: 0.9967 - val_loss: 0.0402 - val_ac

In [21]:
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 13, 13, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_3 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPoolin  (None, 5, 5, 64)          0         
 g2D)                                                            
                                                                 
 flatten_1 (Flatten)         (None, 1600)              0         
                                                                 
 dense_2 (Dense)             (None, 64)               

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

def create_advanced_cnn_model():
    model = Sequential([
        Conv2D(64, (3, 3), activation='relu', input_shape=(28, 28, 1)),
        MaxPooling2D(2, 2),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Conv2D(256, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(len(np.unique(labels)), activation='softmax')  # Adjust number of neurons to match number of classes
    ])
    return model

# Create and compile the advanced CNN model
advanced_cnn_model = create_advanced_cnn_model()
advanced_cnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Reshape and train the model
images_train_reshaped = images_train.reshape((-1, 28, 28, 1))
history_advanced_cnn = advanced_cnn_model.fit(images_train_reshaped, labels_train, epochs=10, batch_size=32, validation_split=0.1)


Epoch 1/10
1624/1624 [==============================] - 14s 8ms/step - loss: 0.2485 - accuracy: 0.9241 - val_loss: 0.0657 - val_accuracy: 0.9822
Epoch 2/10
1624/1624 [==============================] - 15s 9ms/step - loss: 0.0809 - accuracy: 0.9770 - val_loss: 0.0613 - val_accuracy: 0.9808
Epoch 3/10
1624/1624 [==============================] - 16s 10ms/step - loss: 0.0556 - accuracy: 0.9842 - val_loss: 0.0538 - val_accuracy: 0.9858
Epoch 4/10
1624/1624 [==============================] - 15s 9ms/step - loss: 0.0436 - accuracy: 0.9874 - val_loss: 0.0581 - val_accuracy: 0.9863
Epoch 5/10
1624/1624 [==============================] - 15s 9ms/step - loss: 0.0342 - accuracy: 0.9902 - val_loss: 0.0500 - val_accuracy: 0.9889
Epoch 6/10
1624/1624 [==============================] - 16s 10ms/step - loss: 0.0277 - accuracy: 0.9920 - val_loss: 0.0595 - val_accuracy: 0.9858
Epoch 7/10
1624/1624 [==============================] - 17s 10ms/step - loss: 0.0247 - accuracy: 0.9924 - val_loss: 0.0622 - val

In [79]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the Random Forest classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Create and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(images_train_flat, labels_train)

# Evaluate the model
rf_predictions = rf_model.predict(images_test_flat)
rf_accuracy = accuracy_score(labels_test, rf_predictions)
print(f"Random Forest Classifier Accuracy: {rf_accuracy}")


Random Forest Classifier Accuracy: 0.9675720620842572


In [80]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Flatten the images for the SVM
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Create and train the SVM model
svm_model = SVC(kernel='linear', decision_function_shape='ovr')
svm_model.fit(images_train_flat, labels_train)

# Evaluate the model
svm_predictions = svm_model.predict(images_test_flat)
svm_accuracy = accuracy_score(labels_test, svm_predictions)
print(f"SVM Classifier Accuracy: {svm_accuracy}")


SVM Classifier Accuracy: 0.9431125277161863


In [81]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense

def create_simple_nn_model():
    model = Sequential([
        Flatten(input_shape=(28, 28, 1)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(len(np.unique(labels)), activation='softmax')  # Adjust the number of output neurons to the number of classes
    ])
    return model

# Create and compile the simple NN model
simple_nn_model = create_simple_nn_model()
simple_nn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Reshape and train the model
images_train_reshaped = images_train.reshape((-1, 28, 28, 1))
history_simple_nn = simple_nn_model.fit(images_train_reshaped, labels_train, epochs=10, batch_size=32, validation_split=0.1)


Epoch 1/10
1624/1624 [==============================] - 2s 1ms/step - loss: 0.2530 - accuracy: 0.9260 - val_loss: 0.1385 - val_accuracy: 0.9595
Epoch 2/10
1624/1624 [==============================] - 2s 1ms/step - loss: 0.1066 - accuracy: 0.9672 - val_loss: 0.1004 - val_accuracy: 0.9709
Epoch 3/10
1624/1624 [==============================] - 2s 1ms/step - loss: 0.0711 - accuracy: 0.9777 - val_loss: 0.0839 - val_accuracy: 0.9759
Epoch 4/10
1624/1624 [==============================] - 2s 1ms/step - loss: 0.0529 - accuracy: 0.9835 - val_loss: 0.0753 - val_accuracy: 0.9796
Epoch 5/10
1624/1624 [==============================] - 2s 1ms/step - loss: 0.0409 - accuracy: 0.9869 - val_loss: 0.0836 - val_accuracy: 0.9759
Epoch 6/10
1624/1624 [==============================] - 2s 1ms/step - loss: 0.0317 - accuracy: 0.9892 - val_loss: 0.0815 - val_accuracy: 0.9766
Epoch 7/10
1624/1624 [==============================] - 2s 1ms/step - loss: 0.0268 - accuracy: 0.9912 - val_loss: 0.0815 - val_accuracy:

In [82]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the KNN classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Create and train the KNN model
knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(images_train_flat, labels_train)

# Evaluate the model
knn_predictions = knn_model.predict(images_test_flat)
knn_accuracy = accuracy_score(labels_test, knn_predictions)
print(f"KNN Classifier Accuracy: {knn_accuracy}")


KNN Classifier Accuracy: 0.9739467849223947


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the Gradient Boosting classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Create and train the Gradient Boosting model
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
gb_model.fit(images_train_flat, labels_train)

# Evaluate the model
gb_predictions = gb_model.predict(images_test_flat)
gb_accuracy = accuracy_score(labels_test, gb_predictions)
print(f"Gradient Boosting Classifier Accuracy: {gb_accuracy}")


In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the Decision Tree classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Create and train the Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(images_train_flat, labels_train)

# Evaluate the model
dt_predictions = dt_model.predict(images_test_flat)
dt_accuracy = accuracy_score(labels_test, dt_predictions)
print(f"Decision Tree Classifier Accuracy: {dt_accuracy}")


Decision Tree Classifier Accuracy: 0.8600332594235033


In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Flatten the images for Logistic Regression
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Create and train the Logistic Regression model
# Note: For multiclass, Logistic Regression in sklearn uses a one-vs-rest scheme by default
lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(images_train_flat, labels_train)

# Evaluate the model
lr_predictions = lr_model.predict(images_test_flat)
lr_accuracy = accuracy_score(labels_test, lr_predictions)
print(f"Logistic Regression Classifier Accuracy: {lr_accuracy}")


Logistic Regression Classifier Accuracy: 0.9292544345898004


C:\Users\pahad\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the Decision Tree classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different configurations
configurations = [
    {"criterion": "entropy", "max_depth": 10, "splitter": "best"},
    {"criterion": "entropy", "max_depth": 10, "splitter": "random"},
    {"criterion": "entropy", "max_depth": 50, "splitter": "best"},
    {"criterion": "gini", "max_depth": 50, "splitter": "best"},
    {"criterion": "gini", "max_depth": 10, "splitter": "random"},
    {"criterion": "gini", "max_depth": 50, "splitter": "random"}
]

# Iterate over each configuration, train, and evaluate the model
for config in configurations:
    dt_model = DecisionTreeClassifier(criterion=config["criterion"],
                                      max_depth=config["max_depth"],
                                      splitter=config["splitter"],
                                      random_state=42)
    dt_model.fit(images_train_flat, labels_train)
    dt_predictions = dt_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, dt_predictions)
    print(f"Decision Tree with {config}: Accuracy = {accuracy}")


Decision Tree with {'criterion': 'entropy', 'max_depth': 10, 'splitter': 'best'}: Accuracy = 0.8596868070953437
Decision Tree with {'criterion': 'entropy', 'max_depth': 10, 'splitter': 'random'}: Accuracy = 0.8430570953436807
Decision Tree with {'criterion': 'entropy', 'max_depth': 50, 'splitter': 'best'}: Accuracy = 0.8763858093126385
Decision Tree with {'criterion': 'gini', 'max_depth': 50, 'splitter': 'best'}: Accuracy = 0.8600332594235033
Decision Tree with {'criterion': 'gini', 'max_depth': 10, 'splitter': 'random'}: Accuracy = 0.827120288248337
Decision Tree with {'criterion': 'gini', 'max_depth': 50, 'splitter': 'random'}: Accuracy = 0.8612804878048781


In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the Random Forest classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different configurations
configurations = [
    {"criterion": "entropy", "max_depth": 10},
    {"criterion": "entropy", "max_depth": 50},
    {"criterion": "gini", "max_depth": 10},
    {"criterion": "gini", "max_depth": 50}
]

# Iterate over each configuration, train, and evaluate the model
for config in configurations:
    rf_model = RandomForestClassifier(n_estimators=100,
                                      criterion=config["criterion"],
                                      max_depth=config["max_depth"],
                                      random_state=42)
    rf_model.fit(images_train_flat, labels_train)
    rf_predictions = rf_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, rf_predictions)
    print(f"Random Forest with {config}: Accuracy = {accuracy}")


Random Forest with {'criterion': 'entropy', 'max_depth': 10}: Accuracy = 0.9481014412416852
Random Forest with {'criterion': 'entropy', 'max_depth': 50}: Accuracy = 0.9679185144124168
Random Forest with {'criterion': 'gini', 'max_depth': 10}: Accuracy = 0.9381929046563193
Random Forest with {'criterion': 'gini', 'max_depth': 50}: Accuracy = 0.9675720620842572


In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np

# Flatten the images for Logistic Regression
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different configurations
configurations = [
    {"C": 1, "penalty": "l2"},
    {"C": 1, "penalty": "l2"},
    {"C": 10, "penalty": "l2"},
    {"C": 10, "penalty": "l2"},
    {"C": 100, "penalty": "l1"},
    {"C": 0.1, "penalty": "l1"},
    {"C": 1, "penalty": "l1"},
    {"C": 10, "penalty": "l1"},
    {"C": 1, "penalty": "none"}
]

# Iterate over each configuration, train, and evaluate the model
for config in configurations:
    lr_model = LogisticRegression(C=config["C"], penalty=config["penalty"], solver='saga', max_iter=1000, random_state=42)
    lr_model.fit(images_train_flat, labels_train)
    lr_predictions = lr_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, lr_predictions)
    print(f"Logistic Regression with C={config['C']} and penalty={config['penalty']}: Accuracy = {accuracy}")


Logistic Regression with C=0.01 and penalty=l2: Accuracy = 0.9222560975609756


C:\Users\pahad\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Logistic Regression with C=0.1 and penalty=l2: Accuracy = 0.9305016629711752


C:\Users\pahad\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Logistic Regression with C=1 and penalty=l2: Accuracy = 0.9293237250554324
Logistic Regression with C=10 and penalty=l2: Accuracy = 0.9285615299334812
Logistic Regression with C=0.01 and penalty=l1: Accuracy = 0.8937777161862528
Logistic Regression with C=0.1 and penalty=l1: Accuracy = 0.9247505543237251
Logistic Regression with C=1 and penalty=l1: Accuracy = 0.9299473392461197
Logistic Regression with C=10 and penalty=l1: Accuracy = 0.9284922394678492


C:\Users\pahad\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


Logistic Regression with C=1 and penalty=none: Accuracy = 0.9285615299334812


In [28]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for KNN
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different settings for neighbors and p
settings = [
    {"n_neighbors": 3, "p": 1},
    {"n_neighbors": 3, "p": 2},
    {"n_neighbors": 5, "p": 1},
    {"n_neighbors": 5, "p": 2},
    {"n_neighbors": 7, "p": 1},
    {"n_neighbors": 7, "p": 2}
]

# Iterate over each setting, train, and evaluate the model
for setting in settings:
    knn_model = KNeighborsClassifier(n_neighbors=setting["n_neighbors"], weights='distance', p=setting["p"])
    knn_model.fit(images_train_flat, labels_train)
    knn_predictions = knn_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, knn_predictions)
    print(f"KNN with n_neighbors={setting['n_neighbors']} and p={setting['p']}: Accuracy = {accuracy}")


KNN with n_neighbors=3 and p=1: Accuracy = 0.9703436807095344
KNN with n_neighbors=3 and p=2: Accuracy = 0.9751940133037694
KNN with n_neighbors=5 and p=1: Accuracy = 0.9684035476718403
KNN with n_neighbors=5 and p=2: Accuracy = 0.9737389135254989
KNN with n_neighbors=7 and p=1: Accuracy = 0.966809866962306
KNN with n_neighbors=7 and p=2: Accuracy = 0.9721452328159645


In [29]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Flatten the images for the SVM classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different configurations
configurations = [
    {"C": 0.1, "kernel": "linear", "gamma": "scale"},
    {"C": 1, "kernel": "linear", "gamma": "scale"},
    {"C": 0.1, "kernel": "rbf", "gamma": "scale"},
    {"C": 1, "kernel": "rbf", "gamma": "scale"},
    {"C": 0.1, "kernel": "rbf", "gamma": "auto"},
    {"C": 1, "kernel": "rbf", "gamma": "auto"},
    {"C": 0.1, "kernel": "poly", "gamma": "scale"},
    {"C": 1, "kernel": "poly", "gamma": "scale"}
]

# Iterate over each configuration, train, and evaluate the model
for config in configurations:
    svm_model = SVC(C=config["C"], kernel=config["kernel"], gamma=config["gamma"], random_state=42)
    svm_model.fit(images_train_flat, labels_train)
    svm_predictions = svm_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, svm_predictions)
    print(f"SVM with C={config['C']}, kernel={config['kernel']}, gamma={config['gamma']}: Accuracy = {accuracy}")


SVM with C=0.1, kernel=linear, gamma=scale: Accuracy = 0.9465770509977827
SVM with C=1, kernel=linear, gamma=scale: Accuracy = 0.9431125277161863
SVM with C=0.1, kernel=rbf, gamma=scale: Accuracy = 0.9583564301552107
SVM with C=1, kernel=rbf, gamma=scale: Accuracy = 0.9786585365853658
SVM with C=0.1, kernel=rbf, gamma=auto: Accuracy = 0.9156735033259423
SVM with C=1, kernel=rbf, gamma=auto: Accuracy = 0.9441518847006651
SVM with C=0.1, kernel=poly, gamma=scale: Accuracy = 0.948170731707317
SVM with C=1, kernel=poly, gamma=scale: Accuracy = 0.9771341463414634


In [42]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Flatten the images for the SVM classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different configurations
configurations = [
    {"C": 10, "kernel": "linear", "gamma": "scale"},
    {"C": 1, "kernel": "linear", "gamma": "scale"},
    {"C": 10, "kernel": "rbf", "gamma": "scale"},
    {"C": 1, "kernel": "rbf", "gamma": "scale"},
    {"C": 10, "kernel": "rbf", "gamma": "auto"},
    {"C": 1, "kernel": "rbf", "gamma": "auto"},
    {"C": 10, "kernel": "poly", "gamma": "scale"},
    {"C": 1, "kernel": "poly", "gamma": "scale"},
    {"C": 10, "kernel": "sigmoid", "gamma": "scale"}
]

# Iterate over each configuration, train, and evaluate the model
for config in configurations:
    svc_model = SVC(C=config["C"], kernel=config["kernel"], gamma=config["gamma"], random_state=42)
    svc_model.fit(images_train_flat, labels_train)
    svc_predictions = svc_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, svc_predictions)
    print(f"SVC with C={config['C']}, kernel={config['kernel']}, gamma={config['gamma']}: Accuracy = {accuracy}")


SVC with C=10, kernel=linear, gamma=scale: Accuracy = 0.9311945676274944
SVC with C=1, kernel=linear, gamma=scale: Accuracy = 0.9431125277161863
SVC with C=10, kernel=rbf, gamma=scale: Accuracy = 0.9853104212860311
SVC with C=1, kernel=rbf, gamma=scale: Accuracy = 0.9786585365853658
SVC with C=10, kernel=rbf, gamma=auto: Accuracy = 0.9636917960088692
SVC with C=1, kernel=rbf, gamma=auto: Accuracy = 0.9441518847006651
SVC with C=10, kernel=poly, gamma=scale: Accuracy = 0.9808065410199557
SVC with C=1, kernel=poly, gamma=scale: Accuracy = 0.9771341463414634
SVC with C=10, kernel=sigmoid, gamma=scale: Accuracy = 0.6492516629711752


In [34]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Flatten the images for the Gaussian Naive Bayes classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define the Gaussian Naive Bayes classifier with equal priors for 11 classes
equal_prior = 1 / 11
gnb_model = GaussianNB(priors=[equal_prior] * 11)

# Train the model
gnb_model.fit(images_train_flat, labels_train)

# Evaluate the model
gnb_predictions = gnb_model.predict(images_test_flat)
accuracy = accuracy_score(labels_test, gnb_predictions)
print(f"Gaussian Naive Bayes Accuracy: {accuracy}")


Gaussian Naive Bayes Accuracy: 0.6411446784922394


In [35]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

# Flatten the images for the Perceptron classifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different penalty settings
penalties = ['l1', 'l2', 'elasticnet']

# Iterate over each penalty setting, train, and evaluate the model
for penalty in penalties:
    perceptron_model = Perceptron(penalty=penalty, random_state=42)
    perceptron_model.fit(images_train_flat, labels_train)
    perceptron_predictions = perceptron_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, perceptron_predictions)
    print(f"Perceptron with penalty='{penalty}': Accuracy = {accuracy}")


Perceptron with penalty='l1': Accuracy = 0.850609756097561
Perceptron with penalty='l2': Accuracy = 0.8376524390243902
Perceptron with penalty='elasticnet': Accuracy = 0.836890243902439


In [36]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the ExtraTreesClassifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different configurations
configurations = [
    {"criterion": "gini", "max_depth": 10},
    {"criterion": "gini", "max_depth": 50},
    {"criterion": "entropy", "max_depth": 10},
    {"criterion": "entropy", "max_depth": 50}
]

# Iterate over each configuration, train, and evaluate the model
for config in configurations:
    etc_model = ExtraTreesClassifier(criterion=config["criterion"], max_depth=config["max_depth"], random_state=42)
    etc_model.fit(images_train_flat, labels_train)
    etc_predictions = etc_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, etc_predictions)
    print(f"ExtraTreesClassifier with criterion={config['criterion']}, max_depth={config['max_depth']}: Accuracy = {accuracy}")


ExtraTreesClassifier with criterion=gini, max_depth=10: Accuracy = 0.9307095343680709
ExtraTreesClassifier with criterion=gini, max_depth=50: Accuracy = 0.9701358093126385
ExtraTreesClassifier with criterion=entropy, max_depth=10: Accuracy = 0.9350748337028825
ExtraTreesClassifier with criterion=entropy, max_depth=50: Accuracy = 0.9703436807095344


In [37]:
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the PassiveAggressiveClassifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different values for C
c_values = [1, 10, 100]

# Iterate over each value of C, train, and evaluate the model
for c in c_values:
    pac_model = PassiveAggressiveClassifier(C=c, random_state=42, max_iter=1000, tol=1e-3)
    pac_model.fit(images_train_flat, labels_train)
    pac_predictions = pac_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, pac_predictions)
    print(f"PassiveAggressiveClassifier with C={c}: Accuracy = {accuracy}")


PassiveAggressiveClassifier with C=1: Accuracy = 0.867170177383592
PassiveAggressiveClassifier with C=10: Accuracy = 0.867170177383592
PassiveAggressiveClassifier with C=100: Accuracy = 0.867170177383592


In [39]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the SGDClassifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different configurations
configurations = [
    {"loss": "hinge", "penalty": "l2"},
    {"loss": "perceptron", "penalty": "l1"},
    {"loss": "modified_huber", "penalty": "l1"},
    {"loss": "modified_huber", "penalty": "l2"},
    {"loss": "log_loss", "penalty": "elasticnet"},
    {"loss": "hinge", "penalty": "elasticnet"}
]

# Iterate over each configuration, train, and evaluate the model
for config in configurations:
    sgd_model = SGDClassifier(loss=config["loss"], penalty=config["penalty"], random_state=42, max_iter=1000, tol=1e-3)
    sgd_model.fit(images_train_flat, labels_train)
    sgd_predictions = sgd_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, sgd_predictions)
    print(f"SGDClassifier with loss='{config['loss']}' and penalty='{config['penalty']}': Accuracy = {accuracy}")


SGDClassifier with loss='hinge' and penalty='l2': Accuracy = 0.9224639689578714
SGDClassifier with loss='perceptron' and penalty='l1': Accuracy = 0.8869179600886918
SGDClassifier with loss='modified_huber' and penalty='l1': Accuracy = 0.8994595343680709
SGDClassifier with loss='modified_huber' and penalty='l2': Accuracy = 0.9171286031042128
SGDClassifier with loss='log_loss' and penalty='elasticnet': Accuracy = 0.9219096452328159
SGDClassifier with loss='hinge' and penalty='elasticnet': Accuracy = 0.9156042128603105


In [41]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Flatten the images for the KNeighborsClassifier
images_train_flat = images_train.reshape((images_train.shape[0], -1))
images_test_flat = images_test.reshape((images_test.shape[0], -1))

# Define different configurations
configurations = [
    {"weights": "uniform", "n_neighbors": 5, "p": 1},
    {"weights": "uniform", "n_neighbors": 9, "p": 2},
    {"weights": "distance", "n_neighbors": 5, "p": 1},
    {"weights": "distance", "n_neighbors": 9, "p": 2}
    # Add more configurations as needed
]

# Iterate over each configuration, train, and evaluate the model
for config in configurations:
    knn_model = KNeighborsClassifier(weights=config["weights"], n_neighbors=config["n_neighbors"], p=config["p"])
    knn_model.fit(images_train_flat, labels_train)
    knn_predictions = knn_model.predict(images_test_flat)
    accuracy = accuracy_score(labels_test, knn_predictions)
    print(f"KNeighborsClassifier with weights='{config['weights']}', n_neighbors={config['n_neighbors']}, p={config['p']}: Accuracy = {accuracy}")


KNeighborsClassifier with weights='uniform', n_neighbors=5, p=1: Accuracy = 0.9672949002217295
KNeighborsClassifier with weights='uniform', n_neighbors=9, p=2: Accuracy = 0.9702050997782705
KNeighborsClassifier with weights='distance', n_neighbors=5, p=1: Accuracy = 0.9684035476718403
KNeighborsClassifier with weights='distance', n_neighbors=9, p=2: Accuracy = 0.9711751662971175


In [14]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
images_train, images_test, labels_train, labels_test = train_test_split(
    images, labels, test_size=0.2, random_state=42
)

# Reshape images for the CNN
images_train_reshaped = images_train.reshape((-1, 28, 28, 1))

# Train the model
history = model.fit(images_train_reshaped, labels_train, epochs=10, batch_size=32, validation_split=0.1)




NameError: name 'model' is not defined

In [15]:
import tensorflow as tf

def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(11, activation='softmax')  # Adjust based on the label structure
    ])
    return model

model = create_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [16]:
# Reshape images for the CNN and train the model
images_train = images_train.reshape((-1, 28, 28, 1))  # Reshape for the CNN
history = model.fit(images_train, labels_train, epochs=10, batch_size=32, validation_split=0.1)


Epoch 1/10




UnimplementedError: Graph execution error:

Detected at node Cast_1 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>

  File "C:\Users\pahad\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start

  File "C:\Users\pahad\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start

  File "C:\Users\pahad\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever

  File "C:\Users\pahad\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once

  File "C:\Users\pahad\anaconda3\Lib\asyncio\events.py", line 80, in _run

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code

  File "C:\Users\pahad\AppData\Local\Temp\ipykernel_19216\1893078304.py", line 3, in <module>

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1807, in fit

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1401, in train_function

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1384, in step_function

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1373, in run_step

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1155, in train_step

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1249, in compute_metrics

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 620, in update_state

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\utils\metrics_utils.py", line 77, in decorated

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\metrics\base_metric.py", line 140, in update_state_fn

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\metrics\base_metric.py", line 708, in update_state

Cast string to float is not supported
	 [[{{node Cast_1}}]] [Op:__inference_train_function_1407]

In [17]:
# Reshape images for the CNN and evaluate the model
images_test = images_test.reshape((-1, 28, 28, 1))  # Reshape for the CNN
test_loss, test_acc = model.evaluate(images_test, labels_test)
print("Test Accuracy:", test_acc)


UnimplementedError: Graph execution error:

Detected at node Cast_1 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>

  File "C:\Users\pahad\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start

  File "C:\Users\pahad\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start

  File "C:\Users\pahad\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever

  File "C:\Users\pahad\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once

  File "C:\Users\pahad\anaconda3\Lib\asyncio\events.py", line 80, in _run

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code

  File "C:\Users\pahad\AppData\Local\Temp\ipykernel_19216\4107886941.py", line 3, in <module>

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2296, in evaluate

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 4108, in run_step

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2066, in test_function

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2049, in step_function

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2037, in run_step

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1920, in test_step

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1249, in compute_metrics

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 620, in update_state

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\utils\metrics_utils.py", line 77, in decorated

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\metrics\base_metric.py", line 140, in update_state_fn

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\metrics\base_metric.py", line 708, in update_state

Cast string to float is not supported
	 [[{{node Cast_1}}]] [Op:__inference_test_function_1590]

In [18]:
model.fit(images_train, labels_train, epochs=5, batch_size=32)


Epoch 1/5


UnimplementedError: Graph execution error:

Detected at node Cast_1 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>

  File "C:\Users\pahad\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start

  File "C:\Users\pahad\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start

  File "C:\Users\pahad\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever

  File "C:\Users\pahad\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once

  File "C:\Users\pahad\anaconda3\Lib\asyncio\events.py", line 80, in _run

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute

  File "C:\Users\pahad\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes

  File "C:\Users\pahad\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code

  File "C:\Users\pahad\AppData\Local\Temp\ipykernel_19216\1893078304.py", line 3, in <module>

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1807, in fit

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1401, in train_function

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1384, in step_function

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1373, in run_step

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1155, in train_step

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1249, in compute_metrics

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 620, in update_state

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\utils\metrics_utils.py", line 77, in decorated

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\metrics\base_metric.py", line 140, in update_state_fn

  File "C:\Users\pahad\anaconda3\Lib\site-packages\keras\src\metrics\base_metric.py", line 708, in update_state

Cast string to float is not supported
	 [[{{node Cast_1}}]] [Op:__inference_train_function_1407]